# Stage 1: Build the application
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Run the application
FROM node:20-alpine
WORKDIR /app

# Install lm-sensors package
RUN apk add --no-cache lm-sensors

COPY --from=builder /app/dist ./dist
COPY package*.json ./
COPY server.js ./
RUN npm install --omit=dev
CMD ["node", "server.js"]