services:
  sysmon:
    build:
      context: .
      dockerfile: dockerfile
    container_name: sysmon
    restart: unless-stopped
    ports:
      - 4201:3000
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro